# Generated by Django 5.2.8 on 2025-11-13 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
